server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce
      auto-index-creation: true


application:
  file-system:
    folder-path: C:/Users/KudzaiPrichard/Documents/Projects/Kudzai/Pending/ecommerce/src/main/resources/static/uploads/
  security:
    jwt:
      secret-key: 8d4fed75477d160c393db8a22edce23a5ae7971b4533077d89ac0016dd92c879d21791073310294924cb896443a8214cfdc129baa42af8b3030a397382a93532
      expiration: 86400000
      refresh-token:
        expiration: 604800000